// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNM2of7XcnSR4hTzIu1mFWN9mnLXIU0o4',
    appId: '1:595763365436:web:fdc63a50bacd30aee3a539',
    messagingSenderId: '595763365436',
    projectId: 'todo-clean-cubit',
    authDomain: 'todo-clean-cubit.firebaseapp.com',
    storageBucket: 'todo-clean-cubit.appspot.com',
    measurementId: 'G-7MKNW01X5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIEBIdjCz19xeo5ynKKpMl1cIcY4hamKo',
    appId: '1:595763365436:android:b792eec465e57e93e3a539',
    messagingSenderId: '595763365436',
    projectId: 'todo-clean-cubit',
    storageBucket: 'todo-clean-cubit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-FUPxNcNQ6yN3mZZSTfUsZQB7BM12k74',
    appId: '1:595763365436:ios:76f92390b31be94be3a539',
    messagingSenderId: '595763365436',
    projectId: 'todo-clean-cubit',
    storageBucket: 'todo-clean-cubit.appspot.com',
    iosClientId: '595763365436-e10g7qstu239o25v1gt1um7o334v44tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoCleanSolid',
  );
}
